/* 照片按原始比例展示；标题与说明仅在需要时填写。 */
const siteContent = {
  "photos": [
    {
      "id": "mountain-blue",
      "src": "assets/onyria-mountain-blue.jpg",
      "title": "",
      "category": "landscape",
      "label": "云浮岳峙",
      "alt": "蓝天下的雪山岩壁、流云与绿色山坡",
      "description": "",
      "width": 2047,
      "height": 1365,
      "featured": true
    },
    {
      "id": "mountain-mist",
      "src": "assets/onyria-mountain-mist.jpg",
      "title": "",
      "category": "landscape",
      "label": "云浮岳峙",
      "alt": "宽幅云雾中的雪山，右侧是深色岩壁",
      "description": "",
      "width": 2048,
      "height": 1152
    },
    {
      "id": "mountains",
      "src": "assets/onyria-cloud-mountain.jpg",
      "title": "",
      "category": "landscape",
      "label": "云浮岳峙",
      "alt": "流云环绕的雪山与岩壁",
      "description": "",
      "width": 2048,
      "height": 1365
    },
    {
      "id": "mountain-vertical",
      "src": "assets/onyria-mountain-vertical.jpg",
      "title": "",
      "category": "landscape",
      "label": "云浮岳峙",
      "alt": "竖幅雪山与岩壁，云雾穿行于山间",
      "description": "",
      "width": 1366,
      "height": 2048
    },
    {
      "id": "onyria-pano-0006",
      "src": "assets/onyria-pano-0006.png",
      "title": "",
      "category": "landscape",
      "label": "云浮岳峙",
      "alt": "宽幅山谷、森林与穿行的云海",
      "description": "",
      "width": 2048,
      "height": 945
    },
    {
      "id": "onyria-pano-0001",
      "src": "assets/onyria-pano-0001.png",
      "title": "",
      "category": "landscape",
      "label": "云浮岳峙",
      "alt": "宽幅高山原野与云雾笼罩的山谷",
      "description": "",
      "width": 2047,
      "height": 856
    },
    {
      "id": "onyria-dsc00334",
      "src": "assets/onyria-dsc00334.jpg",
      "title": "",
      "category": "landscape",
      "label": "云浮岳峙",
      "alt": "蓝天与流云之间的雪山全景",
      "description": "",
      "width": 2048,
      "height": 937
    },
    {
      "id": "onyria-dsc08677",
      "src": "assets/onyria-dsc08677.jpg",
      "title": "",
      "category": "landscape",
      "label": "云浮岳峙",
      "alt": "浓雾中露出的雪山双峰",
      "description": "",
      "width": 2048,
      "height": 1366
    },
    {
      "id": "onyria-dsc08714",
      "src": "assets/onyria-dsc08714.jpg",
      "title": "",
      "category": "landscape",
      "label": "云浮岳峙",
      "alt": "竖幅雪山与前景深色岩壁",
      "description": "",
      "width": 1366,
      "height": 2048
    },
    {
      "id": "onyria-dsc08714-variant",
      "src": "assets/onyria-dsc08714-variant.jpg",
      "title": "",
      "category": "landscape",
      "label": "云浮岳峙",
      "alt": "竖幅云雾雪山与岩壁的另一幅画面",
      "description": "",
      "width": 1366,
      "height": 2048
    },
    {
      "id": "onyria-dsc09176",
      "src": "assets/onyria-dsc09176.png",
      "title": "",
      "category": "landscape",
      "label": "云浮岳峙",
      "alt": "云海中露出的雪山，前景为深色山脊",
      "description": "",
      "width": 2048,
      "height": 1152
    },
    {
      "id": "onyria-dji0094",
      "src": "assets/onyria-dji0094.jpg",
      "title": "",
      "category": "landscape",
      "label": "云浮岳峙",
      "alt": "蓝天下的雪山群峰与绿色高山原野",
      "description": "",
      "width": 2048,
      "height": 1365
    },
    {
      "id": "onyria-dsc06994",
      "src": "assets/onyria-dsc06994.jpg",
      "title": "",
      "category": "landscape",
      "label": "云浮岳峙",
      "alt": "蓝天下的雪峰、尖锐岩峰与山坡",
      "description": "",
      "width": 2048,
      "height": 1365
    },
    {
      "id": "onyria-dsc06970",
      "src": "assets/onyria-dsc06970.jpg",
      "title": "",
      "category": "landscape",
      "label": "云浮岳峙",
      "alt": "树木、山坡与积雪岩峰",
      "description": "",
      "width": 2048,
      "height": 1366
    },
    {
      "id": "onyria-dsc06981",
      "src": "assets/onyria-dsc06981.jpg",
      "title": "",
      "category": "landscape",
      "label": "云浮岳峙",
      "alt": "阳光下的高山树木、积雪与山峰",
      "description": "",
      "width": 2048,
      "height": 1366
    },
    {
      "id": "onyria-dsc07007",
      "src": "assets/onyria-dsc07007.jpg",
      "title": "",
      "category": "landscape",
      "label": "云浮岳峙",
      "alt": "白云掠过蓝天下的雪山群峰",
      "description": "",
      "width": 2048,
      "height": 1152
    },
    {
      "id": "onyria-flower-foreground",
      "src": "assets/onyria-flower-foreground.jpg",
      "title": "",
      "category": "landscape",
      "label": "云浮岳峙",
      "alt": "竖幅白色花朵与远处的雪山",
      "description": "",
      "width": 1365,
      "height": 2048
    },
    {
      "id": "onyria-dsc00139",
      "src": "assets/onyria-dsc00139.jpg",
      "title": "",
      "category": "landscape",
      "label": "云浮岳峙",
      "alt": "起伏的绿色山坡与云下的尖锐山峰",
      "description": "",
      "width": 2048,
      "height": 1365
    },
    {
      "id": "onyria-dsc05804",
      "src": "assets/onyria-dsc05804.jpg",
      "title": "",
      "category": "landscape",
      "label": "云浮岳峙",
      "alt": "暖色云海之上，雪山从云层中显现",
      "description": "",
      "width": 2048,
      "height": 1152
    },
    {
      "id": "onyria-mountain-dsc08809",
      "src": "assets/onyria-mountain-dsc08809.jpg",
      "title": "",
      "category": "landscape",
      "label": "云浮岳峙",
      "alt": "云雾环绕的高山岩壁与山峰，竖幅构图",
      "description": "",
      "width": 1366,
      "height": 2048
    },
    {
      "id": "onyria-dsc01023",
      "src": "assets/onyria-dsc01023.png",
      "title": "",
      "category": "sunset",
      "label": "屹岳断霞",
      "alt": "金色日光照亮山峰与环绕的云雾",
      "description": "",
      "width": 2048,
      "height": 1151,
      "featured": true
    },
    {
      "id": "onyria-dsc06030",
      "src": "assets/onyria-dsc06030.jpg",
      "title": "",
      "category": "sunset",
      "label": "屹岳断霞",
      "alt": "晚霞映照的雪山与橙红色云海",
      "description": "",
      "width": 2048,
      "height": 1152
    },
    {
      "id": "onyria-dsc03637",
      "src": "assets/onyria-dsc03637.jpg",
      "title": "",
      "category": "sunset",
      "label": "屹岳断霞",
      "alt": "晨光中的雪山与湖面倒影",
      "description": "",
      "width": 2048,
      "height": 1366
    },
    {
      "id": "onyria-dsc00575-gallery",
      "src": "assets/onyria-dsc00575-gallery.png",
      "title": "",
      "category": "sunset",
      "label": "屹岳断霞",
      "alt": "柔和光芒下的雪山与流云",
      "description": "",
      "width": 2048,
      "height": 1366
    },
    {
      "id": "onyria-dsc06943",
      "src": "assets/onyria-dsc06943.jpg",
      "title": "",
      "category": "sunset",
      "label": "屹岳断霞",
      "alt": "蓝天下阳光照亮的雪山尖峰",
      "description": "",
      "width": 2048,
      "height": 1365
    },
    {
      "id": "onyria-dsc06774",
      "src": "assets/onyria-dsc06774.jpg",
      "title": "",
      "category": "sunset",
      "label": "屹岳断霞",
      "alt": "宽幅晚霞雪山与深色山脊",
      "description": "",
      "width": 2048,
      "height": 644
    },
    {
      "id": "onyria-dsc06016",
      "src": "assets/onyria-dsc06016.jpg",
      "title": "",
      "category": "sunset",
      "label": "屹岳断霞",
      "alt": "紫色暮光与长云之下的雪山",
      "description": "",
      "width": 2047,
      "height": 1365
    },
    {
      "id": "onyria-dji0159",
      "src": "assets/onyria-dji0159.jpg",
      "title": "",
      "category": "sunset",
      "label": "屹岳断霞",
      "alt": "金色晨光中的高山与云海",
      "description": "",
      "width": 2048,
      "height": 1365
    },
    {
      "id": "onyria-pano-sunrise",
      "src": "assets/onyria-pano-sunrise.jpg",
      "title": "",
      "category": "sunset",
      "label": "屹岳断霞",
      "alt": "初升阳光与远处山峦，云海穿行于山谷",
      "description": "",
      "width": 2048,
      "height": 1152
    },
    {
      "id": "onyria-sunset-dsc03632",
      "src": "assets/onyria-sunset-dsc03632.jpg",
      "title": "",
      "category": "sunset",
      "label": "屹岳断霞",
      "alt": "暖色霞光下的雪山与湖面倒影",
      "description": "",
      "width": 2048,
      "height": 1366
    },
    {
      "id": "onyria-city-pano-2",
      "src": "assets/onyria-city-pano-2.jpg",
      "title": "",
      "category": "city",
      "label": "城市天际线",
      "alt": "暮色与金色霞光下的城市和远山全景",
      "description": "",
      "width": 2047,
      "height": 744
    },
    {
      "id": "onyria-city-pano-enhanced",
      "src": "assets/onyria-city-pano-enhanced.jpg",
      "title": "",
      "category": "city",
      "label": "城市天际线",
      "alt": "晚霞映照的城市建筑与树木全景",
      "description": "",
      "width": 2048,
      "height": 735
    },
    {
      "id": "onyria-city-dsc00050",
      "src": "assets/onyria-city-dsc00050.jpg",
      "title": "",
      "category": "city",
      "label": "城市天际线",
      "alt": "远山前的工业烟囱与升腾的白色烟雾",
      "description": "",
      "width": 2048,
      "height": 1365
    },
    {
      "id": "onyria-stars-dsc00076",
      "src": "assets/onyria-stars-dsc00076.jpg",
      "title": "",
      "category": "stars",
      "label": "辉光之辰",
      "alt": "云层之间的明月",
      "description": "",
      "width": 2048,
      "height": 1366
    },
    {
      "id": "onyria-stars-dsc00421",
      "src": "assets/onyria-stars-dsc00421.jpg",
      "title": "",
      "category": "stars",
      "label": "辉光之辰",
      "alt": "雪山上空的星轨与青绿色夜空",
      "description": "",
      "width": 2048,
      "height": 1365
    },
    {
      "id": "onyria-stars-dsc00816",
      "src": "assets/onyria-stars-dsc00816.jpg",
      "title": "",
      "category": "stars",
      "label": "辉光之辰",
      "alt": "深蓝夜空中的红色月亮",
      "description": "",
      "width": 2048,
      "height": 1378
    },
    {
      "id": "onyria-stars-milky-way",
      "src": "assets/onyria-stars-milky-way.png",
      "title": "",
      "category": "stars",
      "label": "辉光之辰",
      "alt": "山峦剪影上空的银河与繁星",
      "description": "",
      "width": 2047,
      "height": 1367
    },
    {
      "id": "onyria-stars-mountain-milky-way",
      "src": "assets/onyria-stars-mountain-milky-way.jpg",
      "title": "",
      "category": "stars",
      "label": "辉光之辰",
      "alt": "高山草甸上空的银河，竖幅构图",
      "description": "",
      "width": 1360,
      "height": 2048
    },
    {
      "id": "onyria-stars-dsc07557",
      "src": "assets/onyria-stars-dsc07557.jpg",
      "title": "",
      "category": "stars",
      "label": "辉光之辰",
      "alt": "黑色夜空中的月面与陨石坑",
      "description": "",
      "width": 2048,
      "height": 1366
    }
  ],
  "articles": [],
  "credits": []
};
